# This file stores the configuration details for our
# database setup in different environments

# TODO: store production secrets outside of source control
development:
  adapter: sqlite3
  database: 'development.sqlite3'

test:
  adapter: sqlite3
  database: 'test.sqlite3'
